import Foundation

protocol ReceiptPrinterClient {
    func printEscPosPayload(_ base64Payload: String) async throws
}

enum ReceiptPrinterError: Error {
    case notImplemented
}

final class EpsonWiredReceiptPrinterClient: ReceiptPrinterClient {
    func printEscPosPayload(_ base64Payload: String) async throws {
        // Integrate Epson ePOS iOS SDK here for wired printing.
        // Payload is generated by backend endpoint /v1/admin/orders/:id/receipt/escpos.
        _ = base64Payload
        throw ReceiptPrinterError.notImplemented
    }
}
